name: Build KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex git kmod libssl-dev \
            libelf-dev libncurses-dev python3 dwarves \
            clang lld \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Clone kernel
        run: |
          git clone --depth=1 -b lineage-19.1 https://github.com/Gigaset-dev/android_kernel_gigaset_mt6768 kernel

      - name: Setup KernelSU
        run: |
          cd kernel
          git clone https://github.com/tiann/KernelSU
          cd KernelSU
          git checkout v3.2.4
          cd ..
          ln -sf KernelSU/kernel kernelsu
          sed -i '/menu "General setup"/a source "kernelsu/Kconfig"' Kconfig
          sed -i '/core-y/a core-y += kernelsu/' Makefile

      - name: Build kernel
        run: |
          cd kernel

          export ARCH=arm64
          export SUBARCH=arm64

          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-

          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip

          mkdir -p out
          make O=out k69v1_64_k419_defconfig
          make -j$(nproc) O=out

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image*