name: Build KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison flex libssl-dev make libc6-dev \
          libncurses-dev python3 git curl \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Clone kernel
      run: |
        git clone --depth=1 -b lineage-19.1 \
        https://github.com/Gigaset-dev/android_kernel_gigaset_mt6768 kernel

    - name: Clone clang (Proton)
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Setup KernelSU
      run: |
        cd kernel
        curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -

    - name: Build
      run: |
        export ARCH=arm64
        export SUBARCH=arm64

        export CLANG_PATH=$GITHUB_WORKSPACE/clang/bin
        export PATH=$CLANG_PATH:$PATH

        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

        cd kernel

        # 你的defconfig
        make O=out k69v1_64_k419_defconfig

        make -j$(nproc --all) O=out \
          CC=clang \
          LD=ld.lld \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: kernel/out/arch/arm64/boot/Image*